---
# output: github_document
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: svm-latex-ms.tex
    number_sections: true
title: | 
        | Título
        | 
        | 
author:
- name: Melany Karina Ogando Matos
  affiliation: Estudiante, Universidad Autónoma de Santo Domingo (UASD)
abstract: "Resumen del manuscrito"

keywords: "palabra clave 1, palabra clave 2"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
bibliography: bibliography.bib
# csl: plos-one.csl
csl: apa.csl
header-includes:
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\begin{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
  \usepackage{float} \floatplacement{figure}{H} 
  \newcommand{\beginsupplement}{
    \setcounter{table}{0}
    \renewcommand{\thetable}{S\arabic{table}}
    \setcounter{figure}{0}
    \renewcommand{\thefigure}{S\arabic{figure}}
    }
---

# Introducción

Conocer la dispersion y las formas de agrupamiento de los individuos de una especie, es necesario para su conservacion [@condit1996species, @hubbell1992short]. Las especies no son las mismas en todos los lugares, y estos patrones de variación, en cada uno de los niveles de diversidad: genes, especies y ecosistemas, es el objeto de estudio de la biogeografía. Su objetivo es caracterizar la distribucion de las especies en la actualidad y la variacion geografica de la diversidad en términos de la interacción de los organismos con su ambiente [@lomolino2017biogeography]. La similiridad es una medida simple de la similitud de especies y sus abundancias. Es convencional decir que es lo mismo alta diversidad con alta homogeneidad, lo que es equivalente a poca dominancia [@magurran2004measuring].

Los patrones de biodiversidad son el resultado de la combinacion de los procesos internos de la comunidad de plantas y las condiciones externas del ambiente [@sang2008vascular]. Por ejemplo, la cantidad de nitrogeno en el suelo puede ser asumida como una limitante directa en la distribucion de las especies de plantas [@lange2013physiological]. Numerosas especies de la familia Chrysobalanaceae poseen preferencia por suelos húmedos (@ircCicaco, @PfafLrigida, @sothers2014taxonomic, @grandtner2013dictionary).Esta es una familia de plantas de distribucion pantropical, y cuenta con 18 géneros con 531 especies que se encuentra un 80% en el neotrópico.[@prance2014chrysobalanaceae, @bardon2013origin].

Las especies de Chrysobalaneceae son utilizadas de maneras distintas para el tratamiento y como medicina de algunas enfermedades como la malaria, epilepsia, diarrea y diabetes [@feitosa2012chrysobalanaceae]. Sus usos son frecuentes en la región africana y surámericana, donde son más abundantes [@feitosa2012chrysobalanaceae].
Posee diferentes usos como: El aceite de sus frutos para pinturas y varnices, tambien su madera como material de construccion, combustible y carbón. Ademas es utilizada mezclada con arcilla para hacer vasijas de barro [@prance2014chrysobalanaceae].

La parcela permanente de la isla de Barro Colorado es una reserva de investigacion biologica a cargo del Smithsonian Tropical Research Institute [@croat1978flora].  
Segun @condit1998tropical la distribucion de *Hirtella americana* en la parcela permanente de BCI se encuentra de manera irregular en pequeñas areas isoladas. Sin embargo, los estudios realizados no han demostrado que esta irregularidad se deba a variables ambientales. @croat1978flora menciona que *Hirtella americana* es una de las especies mayor representadas por su densidad en este bosque.

Con el motivo de aplicar estudios de ecología numérica y aprender a utilizarlos en futuras investigaciones, además de descubrir si existen patrones de correlación entre la familia de plantas Chrysobalanaceae y algunas variables ambientales, esta investigación tiene como objetivos conocer la distribución espacial de las especies de la familia Chrysobalanaceae, conoces si se agrupan en grupos discontinuos en función de su composición, y reconocer si estos patrones se encuentran relacionados con alguna variable ambiental. Además de identificar, en caso de que existan, las tendencias de ordenación de la especies de Chrysobalanaceae representadas en BCI y su correspondencia con las variables del ambiente. Este estudio busca estimar la riqueza de la familia Chrysobalanceae en la parcela permanente de Barro Colorado Island y descubir la relación entre la diversidad alpha y las variables ambientales, además de la relación de las especies con la diversidad beta. Tambien identificar si los modelos de distribución de especies predicen la ocurrencia de las especies representadas en el estudio. 

Para realizar un estudio a fondo de la correlación entre esta familia y las variables ambientales era necesario realizar multiples analisis de ecología numerica, por esta razon se realizaron analisis de agrupamiento, tecnicas de ordenacion, analaisis de diversidad y ecología espacial. Ya que cada uno responde a distintas preguntas de investigación. Este estudio intenta resumir los patrones de diversidad asociados a la familia Chrysobalanaceae en la parcela permanente de BCI. 

# Metodología



# Resultados

# Discusión

# Agradecimientos

# Información de soporte

# *Script* reproducible

# Referencias
